// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gh.dev-tim/di-talk/config"
	"gh.dev-tim/di-talk/internal/server"
	"gh.dev-tim/di-talk/internal/storage"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, func(), error) {
	storageStorage, cleanup := storage.NewStorage()
	configConfig := config.NewConfig()
	serverServer, cleanup2 := server.NewServer(storageStorage, configConfig)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}

func InitializeMockServer() (*server.Server, func(), error) {
	mockStorage := storage.NewMockStorage()
	configConfig := config.NewConfig()
	serverServer, cleanup := server.NewServer(mockStorage, configConfig)
	return serverServer, func() {
		cleanup()
	}, nil
}
